version: '3'
services:
  nginx:
    image: "nginx:latest"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_nw

  db:
    image: "postgres:12"
    ports:
      - "5433:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file:
      - .env
    networks:
      - db_nw

  backend:
    build: .
    env_file:
      - .env
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge

volumes:
  dbdata: