version: '3'
services:
  nginx:
    image: "nginx:latest"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_nw

  db:
    image: "postgres:12"
    ports:
      - "5433:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    env_file:
      - .env
    networks:
      - db_nw
  
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass 2332342ff444333S
    ports:
     - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
     - REDIS_REPLICATION_MODE=master
  
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    env_file:
      - .env
    ports:
     - "3000:3000"
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db

  front:
    build:
      context: .
      dockerfile: ./apps/front-office/Dockerfile
    env_file:
      - .env
    ports:
     - "4200:80"
    networks:
      - web_nw
    depends_on:
      - backend

  admin:
    build:
      context: .
      dockerfile: ./apps/admin-pannel/Dockerfile
    env_file:
      - .env
    ports:
     - "4300:80"
    networks:
      - web_nw
    depends_on:
      - backend
  

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge

volumes:
  dbdata: